title: Jake Franek
description: Portfolio + Blog
author: Jake
logo: /static/img/avatar.jpeg
github: https://github.com/jakefrn
about: Digital Creative Strategist <em>Filler text here</em>

baseurl: "http://jakefr.me"
url: "https://jakefrn.github.io/portfolio"

allowsearch: false

disqus_shortname: \#
google_analytics: \#

share:
  twitter_username: \#
  fb_appid: \#


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
