title: Jake Franek
description: Portfolio + Blog
author: Jake
logo: /portfolio/static/img/avatar.png
github: https://github.com/jakefrn
about: Digital Creative Strategist / Dev

baseurl: "https://codeasashu.github.io/hcz-jekyll-blog"
url: "https://codeasashu.github.io/hcz-jekyll-blog"

allowsearch: false

disqus_shortname: dsfsdfsdf
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
