title: Jake Franek
description: Portfolio + Blog
author: Jake
logo: /portfolio/blob/gh-pages/static/img/avatar.jpeg
github: https://github.com/jakefrn
about: Digital Creative Strategist / Dev

baseurl: "http://jakefr.me"
url: "https://jakefrn.github.io/portfolio"

allowsearch: false

disqus_shortname: \#
google_analytics: \#

share:
  twitter_username: \#
  fb_appid: \#


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
